### PR TITLE
university Admission EDA.ipynb

### PR DESCRIPTION
**Pull request by mickynnamdi**
Hello guys,
Based on my review, these are my findings.

### CODE REVIEW

**Comment by gauravjain2** [comment]
1) The University Ranking, directly doesn't influence the chance of admission but when paired with other parameters, they do affect.
2) It is evident from the last graph that the "Research" column has a significant impact on the chance of admission

So I think, we can't discard them right now. More work and visualization is required in this notebook.

**Comment by gogzicole** [comment]
hi @micky i cant seem to view this work as a normal notebook, it opens like an html file, and also i think there is an issue with the way you pushed the work to the repo, can you please do it the right way so we can all view and contribute.

**Comment by mickynnamdi** [comment]
> hi @Micky i cant seem to view this work as a normal notebook, it opens like an html file, and also i think there is an issue with the way you pushed the work to the repo, can you please do it the right way so we can all view and contribute.

I think it is the way you viewed it.
This was what i was complaining initially when i viewed your code. Reload it again. My upload is fine

**Comment by gogzicole** [comment]
1. your plots are missing the required title/ label for easy readability of the graphs.
2. dropping 'research' and 'university_rating' from the dataset shouldn't be done solely based on visual inspection of plots, they should be backed up with proper statistical tests to determine the effect of each predictor on the overall performance of the model.
3. lastly if we are going by the rules of multi-collinearity of a multiple linear regression, as okay and  we can see that of the two columns mentioned only 'university_rating' has a slightly higher positive correlation with chances of admit, so therefore; it might be okay to drop it, but we still have to conduct more statistical tests to support this. and dropping 'research' would be totally bad as its correlation is within the threshold and hence would be a good determining factor in the model building.

**Comment by Echefu-Charles** [comment]
Nice visuals Micky.
However I can not see the backup to your recommendation to drop university rating and research. If there is anything I am missing, please draw my attention to it. Thank you.

**Comment by mickynnamdi** [comment]
Thanks for your responses. I have noted my errors already and have ran further a vif to better understand the decision i initially suggested which was not sufficiently backed

**Comment by Echefu-Charles** [comment]
Alright sir...thanks for the clarification.

Warm Regards,
Echefu Charles.
08134905672.

**Pull request merged**
