### PR TITLE
regression with backward elimination

### PR DESCRIPTION
**Pull request by gogzicole**
1. I first loaded the data set and then replaced the column names with spaces to "__" for easy indexing.
2. I then created multiple linear regression using all the predictors in the dataset.
3. The MAE and RMSE scores were then evaluated, after which i used backward elimination method to analyze which features in the dataset has significant contributions for the sake of optimizing the model.
4. the SOP scores and the university ratings if dropped from the dataset would have no effect on the R-squared and adjusted R-squared values of the model, and hence would contribute little in helping students evaluate their chances of getting admission from a university.

### CODE REVIEW

**Comment by ugoiloh** [comment]
@gogzicole I seem not to understand the essence of introducing the statistical package in your workflow as a model performance check mechanism. You didn't make report based based on your outputs, so as to engage the team.

It would be nice to review and share with the team the conclusions drawn based on your results. 

Thanks

**Comment by gogzicole** [comment]
I made clear conclusions based on the analysis inside the notebook, the
conclusions were made as markdown/comments inside of the codes notebook.

**Comment by mickynnamdi** [comment]
This is quite interesting, even though i did not understand the concept of the coding. The coding arrangement quite hard to articulate. 
Though the concept of dropping the university ratings and perhaps SOP is welcomed because when I ran a correlation relationship between the values and the predicted values, theirs were too high, if I am correct they were the second and third largest value in terms of correlation with the predicted value.

**Comment by Sillians** [comment]
> This is quite interesting, even though i did not understand the concept of the coding. The coding arrangement quite hard to articulate.
> Though the concept of dropping the university ratings and perhaps SOP is welcomed because when I ran a correlation relationship between the values and the predicted values, theirs were too high, if I am correct they were the second and third largest value in terms of correlation with the predicted value.

I'd suggest everyone working on this Project should do a proper documentation on their code, this would enable someone else on this Open source project to explicitly understand your code without reaching out to you for any further explanation of your code.

**Comment by gogzicole** [comment]
check item four of my report at the top, my final verdict based on my analysis with the backward elimination process was given there.
the main purpose of backward elimination is for feature selection, as we all know increasing the amount of predictors(independent variables) in a dataset does not necessarily improve the model created by it, in-fact if two or more of the predictors are strongly correlated with the target variable it is advisable to drop one and take the other. So analyzing the weights of the coefficient, the P-value and the effect of the predictors on the R-squared value, it was gathered that the SOP and University Ratings have little significance in building a model that would help students determine their chances of admission better.

**Pull request merged**
